[package]
name = "rnotify"
version = "0.1.0"
edition = "2021"

[lib]
name = "rnotifylib"
path = "src/lib.rs"

[[bin]]
name = "rnotify"
path = "src/main.rs"

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
serde = { version = "1.0.142", features = ["derive"]}
toml = "0.5.9"
serde_json = "1.0.83"
chrono = "0.4.19"

discord-webhook = { version = "0.1.0", features = ["models"], default-features = false, optional = true }
curl = { version = "0.4.44", default-features = false, features = ["rustls"], optional = true }

lettre = { version = "0.10.1", default-features = false, features = ["serde", "rustls-tls", "builder", "smtp-transport"], optional = true }

[features]
default = ["discord", "telegram", "mail"]
curl = ["dep:curl"]

discord = ["dep:discord-webhook", "curl"]
telegram = ["curl"]
mail = ["dep:lettre"]